apiVersion: apps/v1
kind: Deployment
metadata:
  name: shaik-dj1
  labels:
    app: django-blog

spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-blog
  template:
    metadata:
      labels:
        app: django-blog
    spec:
      containers:
      - name: shaik-dj1
        image: masthan9/dockerimages:3.0
        ports:
        - containerPort: 8000